name: Build and deploy master

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: git config user.name
      run: git config --global user.name "Monumenta CI"
    - name: git config user.email
      run: git config --global user.email "Monumenta.CI@NotARealEmail.com"

    - name: Get Paper
      run: |
          git clone https://github.com/TeamMonumenta/Paper.git
          cd Paper
    - name: Build Paper 1.13
      working-directory: ./Paper
      run: |
          git checkout 1.13
          ./paper jar
    - name: Build Paper 1.15
      working-directory: ./Paper
      run: |
          git checkout 1.15
          ./paper jar
    - name: Build Paper 1.16
      working-directory: ./Paper
      run: |
          git checkout 1.16
          ./paper jar

    - name: Build and deploy to Github Package Registry
      working-directory: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>x-access-token</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        ./deploy.sh
