name: Pull request CI

on: [pull_request]

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup reviewdog
      run: |
        set -o pipefail
        mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin
        echo ::add-path::$HOME/bin

    - name: git config
      run: |
          git config --global user.name "Monumenta CI"
          git config --global user.email "Monumenta.CI@NotARealEmail.com"

    - name: Build Paper
      run: |
          git clone https://github.com/TeamMonumenta/Paper.git
          cd Paper
          git checkout 1.13
          ./paper jar
          git checkout 1.15
          ./paper jar
          git checkout 1.16
          ./paper jar

    - name: Build and report style/pmd/warnings
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -o pipefail
        ./compile.sh --batch-mode | tee compile.log
        ./mvn_version_wrapper.sh checkstyle:checkstyle --batch-mode
        ./mvn_version_wrapper.sh pmd:pmd --batch-mode
        cat compile.log | grep '^\[WARNING\].*\.java' | reviewdog -efm="[WARNING] %f:[%l,%c] %m" -name="compiler-warnings" -reporter=github-pr-check
        cat v1_15_R1/target/checkstyle-result.xml | reviewdog -f=checkstyle -name="checkstyle" -reporter=github-pr-check
        cat plugin/target/checkstyle-result.xml | reviewdog -f=checkstyle -name="checkstyle" -reporter=github-pr-check
        cat adapterapi/target/checkstyle-result.xml | reviewdog -f=checkstyle -name="checkstyle" -reporter=github-pr-check
        cat v1_16_R2/target/checkstyle-result.xml | reviewdog -f=checkstyle -name="checkstyle" -reporter=github-pr-check
        cat v1_15_R1/target/pmd.txt plugin/target/pmd.txt adapterapi/target/pmd.txt v1_16_R2/target/pmd.txt | reviewdog -efm="%f:%l:	%m" -name="pmd" -reporter=github-pr-check
