name: Pull request CI

on: [pull_request]

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup reviewdog
      run: |
        set -o pipefail
        mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin
        echo ::add-path::$HOME/bin

    # Build paper
    - name: git config user.name
      run: git config --global user.name "Monumenta CI"
    - name: git config user.email
      run: git config --global user.email "Monumenta.CI@NotARealEmail.com"
    - name: Get Paper
      run: |
          git clone https://github.com/TeamMonumenta/Paper.git
          cd Paper
    - name: Build Paper 1.15
      working-directory: ./Paper
      run: |
          git checkout 1.15
          ./paper jar
    - name: Build Paper 1.16
      working-directory: ./Paper
      run: |
          git checkout 1.16
          ./paper jar

    # Build & compiler warnings
    - name: Build with Maven
      working-directory: .
      run: |
        set -o pipefail
        ./compile.sh | tee compile.log

    # Checkstyle
    - name: Run checkstyle
      working-directory: .
      run: mvn checkstyle:checkstyle
    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat v1_15_R1/target/checkstyle-result.xml plugin/target/checkstyle-result.xml adapterapi/target/checkstyle-result.xml v1_16_R2/target/checkstyle-result.xml | reviewdog -f=checkstyle -name="checkstyle" -reporter=github-pr-check

    # PMD
    - name: Run pmd
      working-directory: .
      run: mvn pmd:pmd
    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat v1_15_R1/target/pmd.txt plugin/target/pmd.txt adapterapi/target/pmd.txt v1_16_R2/target/pmd.txt | reviewdog -efm="%f:%l:	%m" -name="pmd" -reporter=github-pr-check

    - name: Run reviewdog to report deprecation warnings
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat compile.log | grep '^\[WARNING\].*\.java' | reviewdog -efm="[WARNING] %f:[%l,%c] %m" -name="compiler-warnings" -reporter=github-pr-check
